import { InstagramPost } from "@/types/instagram";

export const SEED_POSTS: InstagramPost[] = [
  {
    id: "1",
    caption: "Behind the scenes of our latest product shoot. The lighting setup took 3 hours but was totally worth it! 🎥✨",
    type: "carousel",
    status: "scheduled",
    scheduledDate: "2026-04-22T10:00",
    hashtags: "#behindthescenes #photography #productshoot",
    createdAt: "2026-04-18T09:00:00Z",
  },
  {
    id: "2",
    caption: "Spring collection is LIVE. Tap the link in bio to shop all new arrivals before they sell out! 🌸",
    type: "photo",
    status: "scheduled",
    scheduledDate: "2026-04-24T14:00",
    hashtags: "#springcollection #newarivals #fashion",
    createdAt: "2026-04-17T11:00:00Z",
  },
  {
    id: "3",
    caption: "Quick tip Tuesday: How to style one piece three different ways. Save this post for later! 💡",
    type: "reel",
    status: "scheduled",
    scheduledDate: "2026-04-29T09:00",
    hashtags: "#tiptuesday #styling #fashion",
    createdAt: "2026-04-16T14:00:00Z",
  },
  {
    id: "4",
    caption: "Exploring the concept of minimalism in modern interior design...",
    type: "carousel",
    status: "draft",
    notes: "Need to finish caption and select final images",
    createdAt: "2026-04-15T10:00:00Z",
  },
  {
    id: "5",
    caption: "Customer spotlight: Meet Sarah, who transformed her living space using our pieces.",
    type: "photo",
    status: "draft",
    notes: "Waiting for customer approval on photo usage",
    createdAt: "2026-04-14T16:00:00Z",
  },
  {
    id: "6",
    caption: "Our founder shares the story behind the brand. 5 years, countless lessons, one vision. ❤️",
    type: "video",
    status: "published",
    publishedDate: "2026-04-15T12:00",
    hashtags: "#brandstory #founder #entrepreneurship",
    createdAt: "2026-04-10T08:00:00Z",
  },
  {
    id: "7",
    caption: "New arrivals are here! The summer drop you've been waiting for is finally live. 🌊☀️",
    type: "photo",
    status: "published",
    publishedDate: "2026-04-12T10:00",
    hashtags: "#newarivals #summerdrop #shopnow",
    createdAt: "2026-04-08T09:00:00Z",
  },
  {
    id: "8",
    caption: "How we give back — our partnership with local artisans in Vietnam.",
    type: "carousel",
    status: "published",
    publishedDate: "2026-04-10T11:00",
    hashtags: "#socialimpact #artisans #sustainability",
    createdAt: "2026-04-05T10:00:00Z",
  },
  {
    id: "9",
    caption: "Year-in-review mega post idea — milestone highlights and community shoutouts",
    type: "carousel",
    status: "backlog",
    notes: "Save for December or anniversary month",
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "10",
    caption: "Collaboration idea with @creativestudio — joint giveaway campaign",
    type: "photo",
    status: "backlog",
    notes: "Reach out to them first, need to align on terms",
    createdAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "11",
    caption: "Reel series: '30 days of inspiration' — daily short-form content",
    type: "reel",
    status: "backlog",
    notes: "Need to plan 30 scripts before starting",
    createdAt: "2026-02-20T10:00:00Z",
  },
];
